name: vanpos

services:
  db:
    container_name: vanpos-db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose to localhost for local development
    environment:
      - POSTGRES_USER=vanpos
      - POSTGRES_PASSWORD=c3304125423f0
      - POSTGRES_DB=vanpos_db
    restart: always

volumes:
  postgres_data:
